In [7]:
import pandas as pd
import numpy as np

In [8]:
es = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia.csv")

In [9]:
es = es.drop(["Unnamed: 0"], axis=1)

In [10]:
es_2007_2015 = es.loc[6:15]

In [11]:
es_2007_2015

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
6,2006,1.13,1.15,1.01,1.29,1.07,67.0,0.956,0.955,63.5,...,NaN,NaN,6.0,37.0,80.110094,85.953953,56.666667,84.354523,71.825787,NaN
7,2007,1.12,1.01,0.97,1.32,1.07,65.0,0.956,0.955,66.2,...,4.54,NaN,6.0,37.0,80.695349,86.112980,56.666667,84.956550,71.825787,NaN
8,2008,1.16,1.16,0.95,1.39,1.09,66.0,0.955,0.955,70.6,...,4.66,NaN,5.0,8.5,90.095031,86.252845,56.666667,85.314565,71.825787,NaN
9,2009,1.12,1.00,1.00,1.39,1.09,66.0,0.966,0.955,72.5,...,4.53,NaN,5.0,8.5,90.413783,85.403987,56.666667,85.595289,71.825787,NaN
10,2010,1.15,1.08,0.99,1.39,1.11,65.0,0.974,0.955,74.1,...,4.30,77.943856,5.0,8.5,90.450256,85.415456,56.666667,85.471377,68.759374,NaN
11,2011,1.18,1.07,1.05,1.39,1.13,64.0,0.974,0.955,76.5,...,4.36,78.401747,5.0,8.5,90.268246,85.358224,56.666667,85.244063,68.759374,NaN
12,2012,1.15,0.95,1.09,1.41,1.11,64.0,0.974,0.955,78.4,...,4.36,77.965932,5.0,8.5,90.355464,85.374812,56.666667,79.985618,68.759374,NaN
13,2013,1.19,0.97,1.18,1.44,1.12,68.0,0.976,0.955,80.0,...,4.48,77.509708,5.0,8.5,90.522325,85.428313,56.666667,74.400225,68.759374,NaN
14,2014,1.37,1.01,1.30,1.67,1.17,69.0,0.972,0.955,84.2,...,4.55,77.746049,5.0,8.5,90.627827,85.462140,58.000000,84.238087,68.089683,NaN
15,2015,1.30,1.04,1.26,1.66,1.19,70.0,0.972,0.955,88.4,...,4.55,78.227271,4.0,6.5,92.748316,82.465381,58.000000,84.410977,76.791460,13.7

In [12]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')

In [13]:
missing_values(es_2007_2015)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 5 - 50.0 %
PR - 0 - 0.0 %
DI - 2 - 20.0 %
SOARS - 1 - 10.0 %
TOGP - 1 - 10.0 %
IPAB - 4 - 40.0 %
PTIP - 1 - 10.0 %
QOES - 1 - 10.0 %
AOLT - 1 - 10.0 %
FLTA - 1 - 10.0 %
EBOF - 1 - 10.0 %
FOWD - 1 - 10.0 %
QOMS - 1 - 10.0 %
CLER - 1 - 10.0 %
WTDA - 1 - 10.0 %
EDBS - 4 - 40.0 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 9 - 90.0 %

In [14]:
mode = es_2007_2015['DI'].mode()[0]
es_2007_2015['DI'].fillna(value=mode, inplace=True)

/var/folders/41/w_0mz3gn2vn0w0dz8wywr8_r0000gn/T/ipykernel_74456/612852558.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  es_2007_2015['DI'].fillna(value=mode, inplace=True)

In [15]:
es_2007_2015 = es_2007_2015.drop(["ELFE", "CFI", "IPAB", "EDBS"], axis=1)

In [16]:
def fill_with_mean(df):
    for feature in df.columns:
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [17]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [18]:
def handle_outliers(df, continuous_features):

    print("Original Shape:", df.shape)
    
    outlier_summary = {}
    
    for feature in continuous_features:
        if feature in df.columns:
            Q1 = df[feature].quantile(0.25)
            Q3 = df[feature].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            
            outlier_mask = (df[feature] < lower_bound) | (df[feature] > upper_bound)
            num_outliers = outlier_mask.sum()
            
            if num_outliers > 0:
                non_outlier_mean = df.loc[~outlier_mask, feature].mean()
                
                df.loc[outlier_mask, feature] = non_outlier_mean
                
                print(f"{feature}: Found {num_outliers} outliers, replaced with mean = {non_outlier_mean:.2f}")
            else:
                print(f"{feature}: No outliers found")
    
    print("\nFinal Shape:", df.shape)
    print(f"Total features processed: {len(continuous_features)}")
    
    return df

In [19]:
es_2007_2015_no_o = handle_outliers(es_2007_2015, continuous_data)

Original Shape: (10, 30)
DBP: Found 3 outliers, replaced with mean = 5.00
DBD: Found 3 outliers, replaced with mean = 8.50
SSB: Found 3 outliers, replaced with mean = 90.39
DWCP: Found 1 outliers, replaced with mean = 85.64
PT: Found 2 outliers, replaced with mean = 84.95
EC: Found 1 outliers, replaced with mean = 70.05
IUI: No outliers found
PMSI: Found 2 outliers, replaced with mean = 56.67

Final Shape: (10, 30)
Total features processed: 9

In [20]:
es_2007_2015_no_o

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,QOMS,CLER,WTDA,DBP,DBD,SSB,DWCP,PMSI,PT,EC
6,2006,1.13,1.15,1.01,1.29,1.07,67.0,0.956,0.955,63.5,...,NaN,NaN,NaN,5.0,8.5,90.390419,85.953953,56.666667,84.354523,71.825787
7,2007,1.12,1.01,0.97,1.32,1.07,65.0,0.956,0.955,66.2,...,4.92,5.07,4.54,5.0,8.5,90.390419,86.112980,56.666667,84.956550,71.825787
8,2008,1.16,1.16,0.95,1.39,1.09,66.0,0.955,0.955,70.6,...,4.84,4.84,4.66,5.0,8.5,90.095031,86.252845,56.666667,85.314565,71.825787
9,2009,1.12,1.00,1.00,1.39,1.09,66.0,0.966,0.955,72.5,...,4.71,4.74,4.53,5.0,8.5,90.413783,85.403987,56.666667,85.595289,71.825787
10,2010,1.15,1.08,0.99,1.39,1.11,65.0,0.974,0.955,74.1,...,4.63,4.79,4.30,5.0,8.5,90.450256,85.415456,56.666667,85.471377,68.759374
11,2011,1.18,1.07,1.05,1.39,1.13,64.0,0.974,0.955,76.5,...,4.56,4.82,4.36,5.0,8.5,90.268246,85.358224,56.666667,85.244063,68.759374
12,2012,1.15,0.95,1.09,1.41,1.11,64.0,0.974,0.955,78.4,...,4.49,4.84,4.36,5.0,8.5,90.355464,85.374812,56.666667,84.948179,68.759374
13,2013,1.19,0.97,1.18,1.44,1.12,68.0,0.976,0.955,80.0,...,4.48,4.94,4.48,5.0,8.5,90.522325,85.428313,56.666667,84.948179,68.759374
14,2014,1.37,1.01,1.30,1.67,1.17,69.0,0.972,0.955,84.2,...,4.63,4.92,4.55,5.0,8.5,90.627827,85.462140,56.666667,84.238087,68.089683
15,2015,1.30,1.04,1.26,1.66,1.19,70.0,0.972,0.955,88.4,...,4.74,4.97,4.55,5.0,8.5,90.390419,85.640301,56.666667,84.410977,70.047814

In [21]:
es_2007_2015_no_o.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2007_2015.csv')

In [22]:
es_2007_2015_no_o = es_2007_2015_no_o.drop(["TIME_PERIOD"], axis=1)

In [23]:
es_2007_2015_l = es_2007_2015_no_o.loc[13]

In [24]:
es_2007_2015_l.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2007_2015_last.csv')

In [25]:
es_2016_2022 = es.loc[16:22]

In [26]:

missing_values(es_2016_2022)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 0 - 0.0 %
PR - 0 - 0.0 %
DI - 0 - 0.0 %
SOARS - 5 - 71.4 %
TOGP - 5 - 71.4 %
IPAB - 5 - 71.4 %
PTIP - 5 - 71.4 %
QOES - 5 - 71.4 %
AOLT - 5 - 71.4 %
FLTA - 5 - 71.4 %
EBOF - 5 - 71.4 %
FOWD - 5 - 71.4 %
QOMS - 5 - 71.4 %
CLER - 5 - 71.4 %
WTDA - 6 - 85.7 %
EDBS - 2 - 28.6 %
DBP - 2 - 28.6 %
DBD - 2 - 28.6 %
SSB - 2 - 28.6 %
DWCP - 2 - 28.6 %
PMSI - 2 - 28.6 %
PT - 2 - 28.6 %
EC - 2 - 28.6 %
ELFE - 0 - 0.0 %

In [27]:
es_2016_2022 = es_2016_2022.drop(["SOARS", "TOGP", "IPAB", "PTIP", "QOES", "AOLT", "FLTA", "EBOF",
                                 "FOWD", "QOMS", "CLER", "WTDA"], axis=1)

In [28]:
mode = es_2016_2022['DBD'].mode()[0]
es_2016_2022['DBD'].fillna(value=mode, inplace=True)
mode = es_2016_2022['DBP'].mode()[0]
es_2016_2022['DBP'].fillna(value=mode, inplace=True)
mode = es_2016_2022['PMSI'].mode()[0]
es_2016_2022['PMSI'].fillna(value=mode, inplace=True)

In [29]:
fill_with_mean(es_2016_2022)

In [30]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [31]:
es_2016_2022_no_o = handle_outliers(es_2016_2022, continuous_data)

Original Shape: (7, 22)
DBP: No outliers found
DBD: No outliers found
EDBS: No outliers found
SSB: Found 1 outliers, replaced with mean = 94.66
DWCP: Found 1 outliers, replaced with mean = 82.50
PT: Found 1 outliers, replaced with mean = 89.53
EC: Found 2 outliers, replaced with mean = 77.58
IUI: No outliers found
PMSI: No outliers found

Final Shape: (7, 22)
Total features processed: 9

In [32]:
es_2016_2022_no_o.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2016_2022.csv')

In [33]:
es_2016_2022_no_o = es_2016_2022_no_o.drop(["TIME_PERIOD"], axis=1)

In [34]:
es_2016_2022_no_o

,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,CFI,...,DI,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
16,1.19,1.05,1.23,1.69,1.21,70.0,0.978,0.955,87.2,51.7,...,7.85,80.664014,3.0,5.5,94.560514,82.478725,58.0,89.528500,77.575862,11.4
17,1.25,1.07,1.20,1.63,1.21,71.0,0.973,0.955,88.1,50.9,...,7.79,80.828594,3.0,5.5,94.623643,82.494332,58.0,89.378009,77.428880,11.8
18,1.20,1.15,1.47,1.54,1.19,73.0,0.973,0.955,89.4,50.5,...,7.97,80.891559,3.0,5.5,94.652164,82.501383,58.0,89.609849,77.616357,12.0
19,1.24,1.14,1.53,1.58,1.18,74.0,0.962,0.947,90.2,50.0,...,7.90,80.918938,3.0,5.5,94.752132,82.526097,58.0,89.609849,77.691347,11.2
20,1.34,1.30,1.58,1.53,1.17,75.0,0.968,0.933,89.1,48.3,...,7.84,80.745858,3.0,5.5,94.661131,82.503600,58.0,89.909583,77.575862,8.5
21,1.39,1.34,1.51,1.55,1.18,74.0,0.975,0.963,91.0,49.9,...,7.84,80.809792,3.0,5.5,94.689166,82.510531,58.0,89.331854,77.571362,9.8
22,1.43,1.34,1.54,1.56,1.20,74.0,0.966,0.969,91.5,50.2,...,7.96,80.809792,3.0,5.5,94.689166,82.510531,58.0,89.331854,77.571362,10.8

In [35]:
es_2016_2022_l = es_2016_2022_no_o.loc[20]

In [36]:
es_2016_2022_l

ROL      1.340000
GE       1.300000
COC      1.580000
RQ       1.530000
VAA      1.170000
CPI     75.000000
FOP      0.968000
JI       0.933000
IUI     89.100000
CFI     48.300000
PR      83.000000
DI       7.840000
EDBS    80.745858
DBP      3.000000
DBD      5.500000
SSB     94.661131
DWCP    82.503600
PMSI    58.000000
PT      89.909583
EC      77.575862
ELFE     8.500000
Name: 20, dtype: float64

In [37]:
es_2016_2022_l.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2014_2020_last.csv')

In [40]:
ee_2022 = es_2016_2022_no_o.loc[22]

In [41]:
ee_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Estonia_2022.csv')