In [1]:
import pandas as pd

In [2]:
dk = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_bn.csv')

dk = dk.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

dk

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,48820.0,22.06,76.414286,6.45,6.42,7.49,17.747,2.747300,24.277939,5.548536,3.69,5.3,11.7,0.000010,304.029304,1.866582
1,48330.0,22.61,76.414286,6.44,6.23,9.47,18.543,3.471527,24.986449,3.835619,0.62,6.5,11.8,0.000009,297.632058,2.784574
2,45680.0,19.85,76.100000,6.43,6.06,13.44,19.948,4.602963,27.815694,-2.111442,1.17,4.2,13.1,0.000009,275.000000,6.041840
3,46190.0,19.37,74.900000,6.37,6.17,15.55,21.888,6.793833,27.336108,-2.441067,-3.57,4.7,13.3,0.000009,292.972973,7.495645
4,46610.0,19.85,74.800000,6.32,6.29,16.31,23.389,6.154324,26.540559,-1.887012,3.94,3.6,12.1,0.000008,282.585278,16.993114
5,46430.0,19.85,74.300000,5.97,5.73,15.77,25.465,5.799405,26.500323,-3.257951,-5.00,4.0,12.0,0.000007,251.520572,6.354829
6,46890.0,19.73,74.300000,5.64,5.45,14.77,27.173,6.229005,25.928504,-1.181728,0.20,4.4,11.9,0.000007,239.037433,8.319061
7,47240.0,19.40,74.700000,5.56,5.43,14.20,29.310,6.455948,25.797420,1.252108,1.86,5.8,12.1,0.000006,244.148936,23.835000
8,47900.0,19.56,75.400000,5.58,5.59,12.15,30.469,6.498281,25.546356,-1.143677,0.61,8.4,12.2,0.000006,257.394366,12.745287
9,48970.0,20.23,76.000000,5.80,5.70,12.15,31.715,6.035122,24.942915,-0.070663,2.50,7.2,11.9,0.000006,270.855148,0.401479
10,50150.0,20.42,76.600000,6.10,5.50,12.38,34.387,6.476226,24.449662,1.457031,1.09,5.6,12.4,0.000006,258.680556,10.241162
11,50830.0,20.58,77.500000,5.80,5.50,10.52,35.159,5.152751,24.381107,0.801500,2.47,4.3,12.7,0.000006,217.962003,6.781235
12,51500.0,20.64,78.300000,5.80,5.60,10.04,37.020,6.009741,24.204777,4.079333,-1.10,2.9,12.5,0.000005,232.530120,8.928446
13,50470.0,19.56,77.800000,5.80,5.50,11.59,31.681,5.640362,24.679988,0.081707,0.36,3.0,12.1,0.000005,216.295026,8.953195
14,53520.0,19.80,79.000000,5.80,5.50,10.81,41.494,6.236804,23.845550,3.868870,4.16,5.7,12.3,0.000005,186.006826,13.806881
15,53290.0,20.84,80.100000,5.80,5.50,10.53,41.368,9.553789,21.681084,3.323468,7.67,10.0,12.4,0.000005,244.112994,12.717471

In [3]:
dk.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_bn_no_context.csv')

In [4]:
dk.columns

Index(['GDPC', 'VABI', 'EMP', 'QOA', 'QOR', 'YUA', 'REST', 'EBSG', 'GGFC',
       'LBGD', 'FDI', 'PC', 'ARP', 'CO2C', 'PAM', 'EUPC'],
      dtype='object')

In [5]:
de = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_bn.csv')

de = de.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

de

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,35330.0,26.46,77.264286,6.710000,6.550000,11.82,10.039,6.389770,17.555365,-0.168868,1.46,-1.2,15.2,0.000010,581.657956,6.196333
1,35750.0,26.06,77.264286,6.670000,6.540000,10.93,10.072,5.783688,17.951098,-0.295519,0.81,-2.6,15.2,0.000010,599.683352,10.012677
2,33880.0,23.87,73.200000,6.610000,6.490000,11.31,10.851,4.768184,19.597935,-2.070729,1.63,-2.4,15.5,0.000009,584.358974,37.999363
3,35370.0,26.06,74.000000,6.610000,6.420000,10.42,11.667,5.103897,19.176892,-3.199506,2.48,-0.6,15.6,0.000010,575.287356,34.793707
4,36700.0,26.31,75.400000,6.450000,6.150000,8.93,12.470,4.852664,18.693432,-0.370659,2.55,1.3,15.8,0.000010,585.349446,39.857009
5,36820.0,26.58,75.800000,6.350000,6.090000,8.12,13.549,6.037145,18.897792,0.092987,1.82,2.4,16.1,0.000010,579.634465,40.920931
6,36910.0,25.91,76.300000,6.080000,6.010000,7.82,13.757,5.772928,19.247998,0.204270,1.76,3.0,16.1,0.000010,587.141971,52.698567
7,37600.0,26.01,76.700000,5.940000,5.880000,7.61,14.381,6.537450,19.210129,0.684115,0.44,5.3,16.7,0.000010,594.640652,39.295143
8,37950.0,25.92,77.000000,5.950000,5.720000,7.33,14.901,7.417530,19.312236,0.679371,1.82,12.0,16.7,0.000010,580.046517,27.981817
9,38550.0,26.22,77.600000,5.900000,5.600000,7.08,14.885,7.263048,19.519072,0.736708,1.64,4.2,16.5,0.000010,588.706740,8.995473
10,39540.0,26.12,78.300000,5.800000,5.500000,6.77,15.472,7.085326,19.459550,0.636665,2.89,3.3,16.1,0.000009,578.090975,22.191244
11,39930.0,25.94,79.000000,5.600000,5.500000,6.22,16.660,5.987124,19.502234,1.111879,4.00,2.7,16.0,0.000009,562.260282,25.953484
12,40300.0,25.63,79.700000,5.500000,5.300000,5.86,17.266,5.638862,19.903024,0.767070,1.91,1.8,14.8,0.000008,561.222770,28.348167
13,38670.0,25.38,78.300000,6.166923,5.980769,7.86,19.090,5.345110,21.731321,-3.657127,4.49,-0.1,16.1,0.000008,508.177008,27.963526
14,40250.0,25.31,79.600000,6.166923,5.980769,6.66,19.302,5.158549,21.674219,-3.522981,2.93,1.0,16.0,0.000008,478.629808,32.395720
15,40710.0,25.69,80.800000,6.166923,5.980769,6.04,20.829,2.496908,21.521327,-2.692237,2.09,-1.4,14.8,0.000008,556.954654,35.097752

In [6]:
de.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_bn_no_context.csv')

In [7]:
pl = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_bn.csv')

pl = pl.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

pl

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,8790.0,29.28,67.985714,3.630000,2.570000,21.39,6.903,-3.803166,18.166685,-1.872662,5.83,-0.3,17.3,0.000009,62.749213,36.747184
1,9180.0,28.82,67.985714,3.690000,1.910000,17.10,7.686,-5.237136,18.626276,-3.397579,2.72,0.5,16.9,0.000009,65.250459,57.512070
2,9410.0,29.96,62.600000,3.740000,2.060000,20.47,8.676,-0.960496,18.707747,-6.157262,3.18,0.8,17.1,0.000008,75.989515,135.142137
3,9740.0,29.70,62.200000,3.650000,2.230000,23.58,9.281,-2.441439,19.149239,-6.142614,3.94,1.0,17.6,0.000009,84.200841,180.098848
4,10250.0,30.39,62.500000,3.650000,2.330000,25.53,10.337,-2.287307,18.077861,-4.112383,3.57,0.0,17.7,0.000009,101.918024,247.386988
5,10400.0,30.23,62.900000,3.810000,2.620000,26.31,10.955,-0.784100,18.008657,-3.437896,1.53,0.0,17.1,0.000008,115.869679,265.323092
6,10480.0,28.68,63.200000,3.910000,3.050000,27.16,11.452,1.117069,18.330801,-4.023830,0.26,-1.2,17.3,0.000008,111.382755,275.386821
7,10900.0,29.94,64.900000,4.020000,3.550000,23.73,11.605,0.407324,18.238027,-3.367862,3.85,-0.3,17.0,0.000008,103.683241,307.471216
8,11390.0,30.99,66.300000,4.070000,3.810000,20.68,11.881,2.067846,17.905031,-2.532527,3.30,-1.0,17.6,0.000008,123.085022,169.995130
9,11740.0,30.67,68.200000,4.300000,4.000000,17.59,11.396,2.946955,17.821550,-2.650770,3.82,0.2,17.3,0.000008,112.220174,76.266802
10,12340.0,28.81,70.000000,4.500000,4.100000,14.76,11.059,2.819160,17.566841,-1.585809,2.38,0.1,15.0,0.000009,103.344746,173.320323
11,13120.0,28.86,71.400000,4.800000,4.100000,11.68,14.936,2.022689,17.469653,0.071103,3.35,-0.1,14.8,0.000009,110.797998,287.205169
12,13720.0,28.83,72.600000,4.800000,4.300000,9.83,15.377,3.644753,17.818308,-0.525643,3.15,-0.4,15.4,0.000008,102.370292,282.668893
13,13720.0,28.57,72.800000,4.043846,3.125385,10.83,16.102,5.608680,18.837162,-7.027947,3.31,-23.6,14.8,0.000008,106.876333,322.255859
14,14750.0,28.49,75.500000,4.043846,3.125385,11.81,15.604,3.201669,18.523151,-2.303009,5.44,-5.0,14.8,0.000009,91.319632,373.491472
15,15190.0,29.18,76.700000,4.043846,3.125385,10.55,16.644,1.683700,18.119129,-3.005692,6.01,-3.7,13.7,0.000008,101.015752,309.967922

In [8]:
pl.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_bn_no_context.csv')

In [9]:
column_index = pl.columns.get_loc('EUPC')
print(column_index)

15

In [10]:
11,0,3
10,1,3
15,6,0
1,8,0
4,8,2
13,9,1
7,10,1
1,10,0
3,10,1
3,11,0
15,12,0
7,13,1
11,13,2
9,13,2
10,14,3
15,14,0
14,15,0
1,15,1

(1, 15, 1)

In [11]:
lt = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_bn.csv')

lt = lt.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

lt

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,10720.0,29.65,73.0,4.400000,4.970000,8.39,16.482,-13.094653,17.451336,-0.493558,6.55,-11.6,19.1,0.000005,19.195046,45.521991
1,11110.0,29.20,73.0,4.610000,5.210000,13.35,17.824,-11.598256,18.666542,-2.844590,3.61,-9.0,20.9,0.000005,27.187500,70.724103
2,9570.0,25.02,67.0,4.220000,5.280000,29.58,19.798,-1.755188,21.205413,-8.626258,-0.96,-13.2,20.3,0.000004,28.797468,337.935130
3,9810.0,26.21,64.3,3.570000,5.270000,35.74,19.639,-2.029481,20.110710,-7.016844,3.01,-28.9,20.5,0.000005,34.838710,281.231582
4,10670.0,28.35,66.9,3.730000,5.230000,32.59,19.943,-2.706873,18.467399,-5.541350,4.36,-16.2,19.2,0.000005,30.693069,309.501994
5,11280.0,28.20,68.5,4.230000,5.170000,26.68,21.437,0.613211,17.543879,-2.893765,1.59,-9.7,18.6,0.000005,36.454849,339.126224
6,11850.0,27.62,69.9,4.320000,5.020000,21.90,22.689,1.457239,16.735544,-2.417272,1.66,-9.0,20.6,0.000005,39.527027,362.332974
7,12400.0,27.73,71.8,4.190000,4.940000,19.26,23.592,1.930309,16.691874,-1.911556,0.74,-7.2,19.1,0.000004,41.836735,344.608645
8,12860.0,26.96,73.3,4.120000,4.960000,16.30,25.748,-0.986813,17.168991,-1.093729,2.50,-10.7,22.2,0.000005,34.707904,29.635159
9,13360.0,26.00,75.2,4.400000,4.900000,14.45,25.612,0.728400,17.029185,-0.460837,2.74,-12.7,21.9,0.000005,32.986111,115.573864
10,14150.0,25.72,76.0,4.400000,4.700000,13.27,26.038,2.294288,16.299364,0.165584,2.90,-11.6,22.9,0.000005,28.521127,170.853686
11,14970.0,25.58,77.8,4.600000,4.700000,11.12,24.695,1.856906,16.217817,0.413734,2.40,-5.0,22.9,0.000005,28.723404,388.976368
12,15710.0,25.26,78.2,4.900000,4.800000,11.85,25.474,5.262450,16.795948,0.441721,6.23,-0.8,20.6,0.000005,32.028470,188.356791
13,15720.0,24.79,76.7,4.283846,5.011538,19.56,26.773,9.072805,18.360545,-6.374068,7.94,0.3,20.9,0.000005,33.807829,514.521647
14,16740.0,24.86,77.4,4.283846,5.011538,14.30,28.167,4.453149,17.497495,-1.419204,3.74,-1.7,20.0,0.000005,28.825623,405.630623
15,17010.0,25.64,79.0,4.283846,5.011538,11.87,29.599,-2.091914,16.744046,-0.897036,3.41,18.1,20.9,0.000005,33.309776,331.287996

In [12]:
lt.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_bn_no_context.csv')

In [13]:
lv = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_bn.csv')

lv = lv.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

lv

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,11540.0,22.75,71.978571,5.390000,3.110000,10.56,29.615,-20.108026,18.600884,0.134663,9.22,-7.7,21.2,0.000004,63.181818,44.685377
1,11270.0,22.84,71.978571,5.590000,2.850000,13.65,29.811,-13.299099,20.701069,-3.172711,4.20,-13.3,25.9,0.000004,94.495413,69.408798
2,9620.0,21.52,66.300000,5.480000,3.190000,33.43,34.317,-2.039931,19.573897,-7.966839,-0.58,-19.8,26.4,0.000004,112.149533,198.581136
3,9470.0,20.86,63.900000,5.440000,3.110000,36.24,30.375,-2.131443,18.789970,-8.375610,2.02,-21.9,20.9,0.000004,84.761905,220.935379
4,9940.0,21.42,66.100000,5.170000,3.100000,31.07,33.478,-6.131271,19.255704,-3.827185,5.72,-14.5,19.0,0.000004,83.980583,248.557865
5,10790.0,21.42,67.900000,5.270000,3.160000,28.56,35.709,-5.548474,17.988056,-1.006694,3.99,-10.3,19.2,0.000004,95.073892,351.810791
6,11130.0,20.82,69.500000,5.390000,3.000000,23.24,37.037,-4.525224,18.281111,-0.749488,3.39,-11.1,19.4,0.000004,111.940299,310.275825
7,11470.0,19.62,70.600000,5.350000,3.090000,19.59,38.629,-2.898049,18.488335,-1.357478,3.45,-7.7,21.2,0.000004,51.758794,358.109379
8,12010.0,19.78,72.500000,5.370000,3.310000,16.32,37.538,-1.188889,18.709564,-1.740458,3.09,-8.7,22.5,0.000004,68.686869,304.485269
9,12430.0,19.17,73.000000,5.100000,3.200000,17.27,37.138,0.526321,18.476344,-0.184948,1.24,-9.6,21.8,0.000004,48.469388,79.129692
10,12970.0,19.78,74.600000,5.200000,3.000000,16.97,39.008,-0.434095,18.670316,0.031418,4.05,-8.1,22.1,0.000004,46.391753,97.751002
11,13630.0,19.35,76.800000,5.500000,3.500000,12.19,40.019,-0.494458,18.535268,-0.633990,1.32,-7.5,23.3,0.000004,44.559585,279.660603
12,13820.0,19.60,77.300000,5.700000,3.600000,12.41,40.929,-0.217946,19.808901,-0.746684,3.37,-6.4,22.9,0.000004,42.931937,381.182419
13,13430.0,20.33,76.900000,5.380769,3.170769,14.87,42.132,1.435286,20.889693,-3.934799,2.81,-7.6,21.6,0.000004,48.947368,311.526542
14,14480.0,21.09,75.300000,5.380769,3.170769,14.78,42.112,-3.174062,21.731000,-6.941226,9.78,-9.3,23.4,0.000004,55.319149,300.408063
15,14750.0,20.72,77.000000,5.380769,3.170769,15.27,43.786,-4.888329,20.486894,-4.914751,3.20,3.9,22.5,0.000004,75.992908,307.829543

In [14]:
lv.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_bn_no_context.csv')

In [15]:
column_index = lv.columns.get_loc('PAM')
print(column_index)

14

In [16]:
9,1,0
3,3,1
15,3,2
15,4,0
15,5,2
3,5,3
3,7,3
4,7,3
1,9,1
15,10,2
1,10,0
12,14,1
8,15,0
4,15,0
3,15,2

(3, 15, 2)

In [17]:
ee = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn.csv')

ee = ee.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,15790.0,26.84,76.05,4.99,3.78,10.10,17.139,-8.790011,15.899159,3.169094,13.51,-3.3,19.4,0.000017,32.835821,55.095409
1,15030.0,26.13,76.05,5.10,4.00,12.03,18.811,-3.904339,18.436467,-2.025402,8.12,-2.0,19.5,0.000016,46.268657,84.791865
2,12850.0,23.28,70.50,4.87,4.22,27.41,23.009,4.963764,20.533284,-2.239512,9.51,-1.8,19.7,0.000013,57.142857,356.850436
3,13190.0,24.03,67.60,4.55,4.53,32.94,24.575,6.420120,19.561652,-0.609832,13.28,-2.7,15.8,0.000017,63.157895,396.929938
4,14240.0,25.35,71.00,4.39,4.49,22.39,25.515,5.793163,18.294990,0.526226,4.80,-3.3,17.5,0.000017,46.616541,179.744167
5,14810.0,24.63,73.10,4.46,4.22,20.86,25.586,1.640113,18.024258,-0.123296,7.69,-3.8,17.5,0.000016,15.151515,499.062449
6,15130.0,24.68,74.10,4.14,4.20,18.70,25.356,2.306589,18.399173,0.273440,4.31,-3.3,18.6,0.000018,18.939394,514.084077
7,15680.0,24.11,75.00,3.78,4.39,14.98,26.130,3.225526,18.439013,0.975175,6.59,-1.9,21.8,0.000017,33.587786,287.150438
8,16000.0,23.12,76.70,3.73,4.53,14.34,28.987,3.561763,19.223265,0.119938,-3.07,0.8,21.6,0.000016,22.727273,79.744303
9,16460.0,23.23,77.00,4.50,4.70,14.13,29.232,3.207492,19.332394,-0.181622,3.77,-0.2,21.7,0.000016,21.969697,146.147423
10,17390.0,23.18,79.20,5.10,4.70,12.18,29.538,3.975466,18.874982,-0.229889,6.32,2.7,21.0,0.000017,28.030303,215.240805
11,17990.0,23.29,79.70,4.60,4.70,12.08,29.970,2.315765,18.762851,-0.760256,4.08,4.3,21.9,0.000018,18.181818,329.721657
12,18580.0,22.31,80.50,4.60,4.70,11.62,31.730,3.686161,19.081933,0.196333,9.77,3.1,21.7,0.000012,23.308271,489.642208
13,17990.0,21.77,79.10,4.60,4.70,18.42,30.069,-1.083534,20.508689,-5.358715,12.01,0.8,20.7,0.000009,15.789474,399.035305
14,19450.0,22.65,79.30,4.60,4.70,16.62,37.342,-1.302298,19.815687,-2.149653,20.31,1.3,20.6,0.000010,18.796992,428.656702
15,19190.0,23.34,81.90,4.60,4.70,18.39,38.542,-1.236321,19.291309,-0.692318,4.89,25.3,22.8,0.000011,30.320988,405.044191

In [18]:
ee.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_bn_no_context.csv')

In [19]:
fi = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn.csv')

fi = fi.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,41650.0,30.67,73.892857,6.310000,5.64,16.43,29.561,4.794744,20.768314,5.292982,8.57,4.4,13.0,0.000013,341.020794,6.033898
1,41780.0,29.57,73.892857,6.430000,5.84,16.34,31.071,3.615903,21.566205,4.569814,6.79,4.9,13.6,0.000011,338.794727,9.016756
2,38230.0,25.66,72.600000,6.330000,5.89,21.38,31.045,2.038683,24.069112,-1.860401,-3.48,4.7,13.8,0.000011,338.202247,34.478428
3,39260.0,26.19,71.900000,6.150000,5.86,21.29,32.166,1.364890,23.685735,-2.369424,4.90,4.4,13.1,0.000012,322.947761,27.559638
4,40010.0,25.04,72.700000,6.160000,5.83,19.93,32.532,-0.781159,23.401887,-0.488730,-2.18,4.8,13.7,0.000011,306.122449,44.801132
5,39210.0,23.36,73.000000,6.200000,6.09,18.87,34.222,-1.560551,24.176307,-1.104413,1.92,4.7,13.2,0.000010,313.863216,40.733725
6,38650.0,23.30,72.500000,6.220000,6.10,19.82,36.630,-0.984781,24.635744,-1.825088,-1.83,4.5,11.8,0.000010,293.382353,61.528149
7,38300.0,23.06,72.200000,6.170000,5.87,20.45,38.633,-1.015764,24.631415,-2.267616,6.42,3.8,12.8,0.000009,259.890110,39.404991
8,38350.0,23.30,71.800000,6.050000,5.78,22.30,39.230,-0.398683,24.522817,-1.810725,7.54,2.8,12.4,0.000008,235.218978,16.873910
9,39230.0,23.48,72.400000,6.200000,5.70,20.06,38.943,-1.055550,23.868773,-1.298460,2.19,2.9,11.6,0.000009,229.090909,18.148198
10,40430.0,24.47,73.200000,6.300000,5.40,20.04,40.857,0.393848,22.949098,-0.443691,6.66,1.8,11.5,0.000008,252.268603,38.082226
11,40860.0,24.11,75.300000,6.200000,5.30,16.96,41.185,-0.845174,23.055130,-0.006899,-3.84,0.9,12.0,0.000009,251.268116,33.548519
12,41370.0,24.15,76.200000,6.300000,5.30,17.13,42.807,0.672486,23.318576,0.316119,6.10,1.3,11.6,0.000008,239.311594,28.720087
13,40270.0,24.23,75.500000,6.232308,5.30,21.19,43.939,0.244091,24.420548,-5.502841,-0.94,1.5,12.2,0.000007,287.160940,26.447993
14,41270.0,24.23,76.800000,6.232308,5.30,17.06,42.819,0.054268,24.795388,-2.322281,8.01,2.6,10.8,0.000007,281.046931,40.928569
15,41470.0,25.18,78.400000,6.232308,5.30,14.14,47.740,-1.992973,24.149022,-0.031939,4.67,2.8,12.7,0.000007,279.316547,32.630811

In [20]:
fi.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_bn_no_context.csv')

In [21]:
se = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_bn.csv')

se = se.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

se

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,44430.0,25.02,79.7,6.030000,5.65,19.26,43.224,5.900063,24.205811,3.214195,9.42,7.6,10.5,0.000006,276.174863,3.554298
1,43680.0,24.15,80.0,6.020000,5.63,20.21,43.922,5.218714,24.785451,2.032230,8.05,8.0,13.5,0.000006,276.464208,5.290971
2,41470.0,22.33,77.9,6.040000,5.69,25.02,47.024,4.958800,26.132116,-0.614954,2.06,9.1,14.4,0.000005,235.053763,19.503994
3,43480.0,23.86,77.7,6.200000,5.71,24.76,46.099,4.661454,25.187785,-0.240938,0.13,8.0,14.8,0.000006,234.115139,18.684230
4,44510.0,23.73,79.0,6.250000,5.66,22.78,47.632,4.436392,25.092481,0.015331,1.22,7.1,15.4,0.000005,212.063492,33.708495
5,44010.0,23.11,79.1,5.970000,5.58,23.61,49.403,4.367928,25.878585,-0.914026,0.78,7.7,15.2,0.000005,240.336134,11.559979
6,44130.0,21.98,79.4,5.730000,5.52,23.52,50.153,3.831176,26.318281,-1.371356,0.25,9.3,16.0,0.000005,242.916667,26.080148
7,44690.0,21.61,79.6,5.670000,5.50,22.82,51.151,3.093335,26.275487,-1.129253,-1.05,10.6,15.6,0.000004,204.536082,35.538469
8,46160.0,22.28,80.1,5.600000,5.36,20.36,52.220,3.259861,25.892770,0.377740,1.95,10.6,16.3,0.000004,207.959184,8.000893
9,46590.0,21.96,80.8,5.700000,5.30,18.90,52.597,2.557094,26.439038,1.576112,3.01,14.5,16.2,0.000004,204.838710,5.269573
10,46800.0,22.16,81.4,5.800000,5.50,17.88,53.390,1.867221,26.261956,1.661827,4.53,12.4,15.8,0.000004,198.011928,15.072472
11,47080.0,22.19,82.0,5.800000,5.60,17.40,53.916,1.652194,26.255213,1.473616,-0.13,10.8,16.4,0.000004,180.550098,24.303753
12,47790.0,22.29,81.7,5.700000,5.30,20.09,55.785,3.961344,25.835993,1.471518,2.98,9.5,17.1,0.000004,175.291829,17.055225
13,46550.0,21.81,80.2,5.885385,5.30,23.90,60.124,4.189104,26.531166,-2.994377,3.40,5.0,16.1,0.000004,170.434783,19.839044
14,48690.0,23.06,80.4,5.885385,5.30,24.60,62.527,4.321306,25.752442,-0.653958,9.10,7.0,15.7,0.000004,169.961612,19.179014
15,48780.0,24.02,82.0,5.885385,5.30,21.61,66.287,1.905541,25.323965,0.754005,9.30,6.6,16.0,0.000004,198.938672,22.253804

In [22]:
se.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_bn_no_context.csv')