In [1]:
import pandas as pd

In [2]:
dk = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_tcdf.csv')

dk = dk.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

dk

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-0.044236,1.993087,0.000000,1.507482,1.967246,-1.983317,-1.547192,-2.152115,-0.624255,1.821767,0.820083,-0.026674,-1.341362,1.925948,1.582223,-1.295339
1,-0.248239,2.606130,0.000000,1.475493,1.400381,-1.170806,-1.439399,-1.652362,-0.135110,1.170145,-0.229760,0.613497,-1.110590,1.520047,1.378180,-1.134649
2,-1.351525,-0.470232,-0.187326,1.443504,0.893186,0.458320,-1.249136,-0.871617,1.818158,-1.092217,-0.041677,-0.613497,1.889445,1.240296,0.656321,-0.564481
3,-1.139195,-1.005251,-0.902573,1.251570,1.221371,1.324177,-0.986423,0.640190,1.487058,-1.217612,-1.662607,-0.346759,2.350989,1.227678,1.229577,-0.309999
4,-0.964334,-0.470232,-0.962177,1.091625,1.579391,1.636050,-0.783160,0.198898,0.937824,-1.006840,0.905575,-0.933582,-0.418274,0.638252,0.898257,1.352487
5,-1.039275,-0.470232,-1.260196,-0.027990,-0.091370,1.414456,-0.502031,-0.046014,0.910045,-1.528369,-2.151621,-0.720192,-0.649046,0.073942,-0.092565,-0.509694
6,-0.847761,-0.603987,-1.260196,-1.083627,-0.926750,1.004097,-0.270736,0.250432,0.515270,-0.738538,-0.373387,-0.506802,-0.879818,0.252349,-0.490721,-0.165864
7,-0.702044,-0.971813,-1.021781,-1.339539,-0.986420,0.770193,0.018654,0.407034,0.424772,0.187334,0.194281,0.240064,-0.418274,-0.230372,-0.327687,2.550126
8,-0.427263,-0.793473,-0.604554,-1.275561,-0.509060,-0.071043,0.175604,0.436245,0.251441,-0.724063,-0.233180,1.627101,-0.187502,-0.492698,0.094782,0.608925
9,0.018215,-0.046675,-0.246930,-0.571803,-0.180875,-0.071043,0.344336,0.116643,-0.165166,-0.315871,0.413140,0.986930,-0.879818,-0.350028,0.524119,-1.551799
10,0.509489,0.165104,0.110693,0.387867,-0.777575,0.023339,0.706175,0.421026,-0.505700,0.265290,-0.069035,0.133369,0.274042,-0.601847,0.135805,0.170590
11,0.792597,0.343443,0.647128,-0.571803,-0.777575,-0.739929,0.810718,-0.492236,-0.553029,0.015915,0.402881,-0.560149,0.966357,-0.621560,-1.162931,-0.435053
12,1.071541,0.410321,1.123959,-0.571803,-0.479225,-0.936901,1.062732,0.099129,-0.674765,1.262858,-0.817945,-1.307015,0.504814,-1.006274,-0.698274,-0.059194
13,0.642716,-0.793473,0.825940,-0.571803,-0.777575,-0.300844,0.339732,-0.155761,-0.346687,-0.257906,-0.318672,-1.253668,-0.418274,-1.263172,-1.216100,-0.054862
14,1.912536,-0.525963,1.541186,-0.571803,-0.777575,-0.620925,1.668595,0.255813,-0.922770,1.182794,0.980808,0.186716,0.043270,-1.088887,-2.182155,0.794752
15,1.816779,0.633246,2.196829,-0.571803,-0.777575,-0.735825,1.651532,2.544694,-2.417085,0.975314,2.181116,2.480662,0.274042,-1.223675,-0.328833,0.604056

In [3]:
dk.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/dk_no_context.csv')

In [4]:
dk.columns

Index(['GDPC', 'VABI', 'EMP', 'QOA', 'QOR', 'YUA', 'REST', 'EBSG', 'GGFC',
       'LBGD', 'FDI', 'PC', 'ARP', 'CO2C', 'PAM', 'EUPC'],
      dtype='object')

In [5]:
de = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_tcdf.csv')

de = de.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

de

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-1.216359,1.012551,7.146179e-15,1.487576e+00,1.508163e+00,1.935508,-1.457643,0.573955,-1.733416,0.315491,-0.699711,-0.861067,-1.076826,0.942835,0.411627,-1.885554
1,-1.006663,0.357311,7.146179e-15,1.378010e+00,1.481668e+00,1.463077,-1.447322,0.048785,-1.391156,0.239042,-1.340292,-1.263737,-1.076826,1.017248,0.991621,-1.575685
2,-1.940308,-3.230130,-2.043798e+00,1.213660e+00,1.349195e+00,1.664789,-1.203674,-0.831149,0.033154,-0.832506,-0.532175,-1.206212,-0.559950,0.112957,0.498536,0.696700
3,-1.196388,0.357311,-1.641504e+00,1.213660e+00,1.163731e+00,1.192358,-0.948454,-0.540254,-0.330996,-1.513856,0.305508,-0.688494,-0.387657,0.840944,0.206643,0.436416
4,-0.532352,0.766836,-9.374890e-01,7.753937e-01,4.483729e-01,0.401434,-0.697300,-0.757947,-0.749129,0.193687,0.374493,-0.142013,-0.043073,0.658546,0.530406,0.847532
5,-0.472439,1.209123,-7.363420e-01,5.014775e-01,2.894043e-01,-0.028532,-0.359822,0.268406,-0.572383,0.473552,-0.344928,0.174370,0.473804,0.818150,0.346518,0.933917
6,-0.427504,0.111596,-4.849081e-01,-2.380964e-01,7.744622e-02,-0.187778,-0.294766,0.039462,-0.269498,0.540724,-0.404059,0.346943,0.473804,1.058215,0.588083,1.890205
7,-0.083004,0.275406,-2.837610e-01,-6.215792e-01,-2.669857e-01,-0.299251,-0.099598,0.701921,-0.302251,0.830367,-1.704930,1.008473,1.507557,0.408052,0.829365,0.801911
8,0.091742,0.127977,-1.329007e-01,-5.941876e-01,-6.909018e-01,-0.447881,0.063043,1.464510,-0.213941,0.827503,-0.344928,2.935536,1.507557,0.397927,0.359776,-0.116677
9,0.391307,0.619407,1.688199e-01,-7.311457e-01,-1.008839e+00,-0.580586,0.058038,1.330652,-0.035053,0.862113,-0.522320,0.692089,1.162972,0.367671,0.638432,-1.658277
10,0.885589,0.455597,5.208272e-01,-1.005062e+00,-1.273787e+00,-0.745141,0.241634,1.176656,-0.086533,0.801725,0.709566,0.433230,0.473804,0.101184,0.296854,-0.586843
11,1.080307,0.160739,8.728346e-01,-1.552895e+00,-1.273787e+00,-1.037093,0.613204,0.225063,-0.049616,1.088573,1.803481,0.260657,0.301511,-0.349852,-0.212523,-0.281368
12,1.265038,-0.347073,1.224842e+00,-1.826811e+00,-1.803682e+00,-1.228189,0.802743,-0.076707,0.297018,0.880440,-0.256232,0.001798,-1.765995,-1.124086,-0.245906,-0.086931
13,0.451220,-0.756598,5.208272e-01,2.432865e-15,2.353207e-15,-0.166545,1.373235,-0.331242,1.878269,-1.790085,2.286380,-0.544683,0.473804,-1.945156,-1.952734,-0.118162
14,1.240075,-0.871265,1.174555e+00,2.432865e-15,2.353207e-15,-0.803531,1.439542,-0.492898,1.828882,-1.709112,0.748987,-0.228300,0.301511,-1.523318,-2.903460,0.241711
15,1.469741,-0.248787,1.777996e+00,2.432865e-15,2.353207e-15,-1.132641,1.917141,-2.799212,1.696650,-1.207659,-0.078841,-0.918591,-1.765995,-1.781316,-0.383239,0.461103

In [6]:
de.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/de_no_context.csv')

In [7]:
pl = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_tcdf.csv')

pl = pl.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

pl

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-1.415421,-0.232693,0.000000,-1.118578e+00,-0.728098,0.520081,-1.680168,-1.538309,-0.097148,0.729229,1.651317,0.305565,0.748491,1.022969,-2.069287,-1.830687
1,-1.216854,-0.819207,0.000000,-9.564048e-01,-1.593346,-0.204906,-1.415219,-2.036415,0.924607,-0.075492,-0.531721,0.444261,0.437430,0.453300,-1.923512,-1.621839
2,-1.099751,0.634328,-1.157587,-8.212606e-01,-1.396699,0.364606,-1.080226,-0.550875,1.105732,-1.531817,-0.208828,0.496272,0.592960,-0.856918,-1.297630,-0.841057
3,-0.931734,0.302820,-1.243562,-1.064520e+00,-1.173832,0.890180,-0.875508,-1.065298,2.087249,-1.524087,0.324648,0.530946,0.981786,1.000903,-0.819066,-0.388894
4,-0.672070,1.182591,-1.179081,-1.064520e+00,-1.042734,1.219720,-0.518182,-1.011758,-0.294619,-0.452705,0.064930,0.357576,1.059552,0.743702,0.213507,0.287872
5,-0.595699,0.978586,-1.093106,-6.320588e-01,-0.662549,1.351535,-0.309065,-0.489602,-0.448472,-0.096768,-1.367031,0.357576,0.592960,0.035308,1.026623,0.468269
6,-0.554967,-0.997711,-1.028625,-3.617705e-01,-0.098828,1.495181,-0.140892,0.170791,0.267713,-0.405974,-2.258496,0.149532,0.748491,-0.403924,0.765121,0.569487
7,-0.341127,0.608827,-0.663233,-6.445337e-02,0.556663,0.915529,-0.089120,-0.075747,0.061459,-0.059810,0.261473,0.305565,0.515195,-1.610933,0.316386,0.892184
8,-0.091646,1.947609,-0.362322,7.069079e-02,0.897518,0.400095,0.004272,0.501055,-0.678851,0.381008,-0.124595,0.184206,0.981786,-1.277989,1.447139,-0.490514
9,0.086554,1.539599,0.046058,6.923539e-01,1.146604,-0.122099,-0.159841,0.806423,-0.864445,0.318610,0.240415,0.392250,0.748491,-0.185535,0.813926,-1.433209
10,0.392041,-0.831957,0.432944,1.232931e+00,1.277702,-0.600354,-0.273874,0.762032,-1.430711,0.880605,-0.770381,0.374913,-1.040110,1.143168,0.296658,-0.457070
11,0.789173,-0.768206,0.733855,2.043795e+00,1.277702,-1.120858,1.038013,0.485369,-1.646776,1.754982,-0.089498,0.340239,-1.195641,1.085152,0.731040,0.688353
12,1.094660,-0.806457,0.991779,2.043795e+00,1.539898,-1.433498,1.187238,1.048812,-0.871653,1.440070,-0.229886,0.288228,-0.729049,-0.644119,0.239866,0.642728
13,1.094660,-1.137965,1.034766,-2.400642e-15,0.000000,-1.264503,1.432561,1.731004,1.393446,-1.991291,-0.117575,-3.733962,-1.195641,-1.789286,0.502482,1.040884
14,1.619078,-1.239967,1.615095,-2.400642e-15,0.000000,-1.098888,1.264049,0.894901,0.695342,0.502128,1.377560,-0.509275,-1.195641,1.385827,-0.404177,1.556198
15,1.843102,-0.360196,1.873019,-2.400642e-15,0.000000,-1.311822,1.615961,0.367617,-0.202874,0.131312,1.777666,-0.283894,-2.051059,-0.101626,0.160922,0.917295

In [8]:
pl.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/pl_no_context.csv')

In [9]:
column_index = pl.columns.get_loc('EUPC')
print(column_index)

15

In [10]:
11,0,3
10,1,3
15,6,0
1,8,0
4,8,2
13,9,1
7,10,1
1,10,0
3,10,1
3,11,0
15,12,0
7,13,1
11,13,2
9,13,2
10,14,3
15,14,0
14,15,0
1,15,1

(1, 15, 1)

In [11]:
lt = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_tcdf.csv')

lt = lt.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

lt

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-0.954496,1.933703,3.211646e-15,0.381049,-2.322140e-01,-1.289612,-1.858093,-2.343854,-0.175526,0.751926,1.518002,-0.373220,-1.226729,0.219845,-2.473097,-1.577326
1,-0.790913,1.641271,3.211646e-15,1.069965,1.109467e+00,-0.672973,-1.494726,-2.067305,0.730999,-0.103322,0.154756,-0.099394,0.186463,0.735268,-0.925241,-1.395990
2,-1.436856,-1.075092,-1.355997e+00,-0.209451,1.500791e+00,1.344780,-0.960235,-0.248207,2.624957,-2.206551,-1.964303,-0.541729,-0.284601,-2.368135,-0.613447,0.526669
3,-1.336190,-0.301773,-1.966196e+00,-2.341811,1.444887e+00,2.110607,-1.003287,-0.298899,1.808326,-1.621085,-0.123457,-2.195220,-0.127580,-0.956294,0.556528,0.118671
4,-0.975468,1.088901,-1.378597e+00,-1.816922,1.221274e+00,1.718991,-0.920974,-0.424088,0.582441,-1.084337,0.502523,-0.857683,-1.148218,-0.159676,-0.246336,0.322085
5,-0.719608,0.991424,-1.016998e+00,-0.176645,8.858535e-01,0.984245,-0.516451,0.189497,-0.106490,-0.121210,-0.781896,-0.173116,-1.619282,0.327443,0.869518,0.535240
6,-0.480525,0.614512,-7.005985e-01,0.118605,4.730286e-02,0.389984,-0.177453,0.345482,-0.709496,0.052126,-0.749438,-0.099394,-0.049069,-1.014396,1.464490,0.702219
7,-0.249831,0.685995,-2.711994e-01,-0.307867,-3.999242e-01,0.061773,0.067048,0.432910,-0.742073,0.236093,-1.176032,0.090178,-1.226729,-1.100302,1.911799,0.574687
8,-0.056887,0.185613,6.779986e-02,-0.537506,-2.881174e-01,-0.306222,0.650818,-0.106203,-0.386151,0.533599,-0.359939,-0.278434,1.207101,-0.288417,0.531196,-1.691636
9,0.152835,-0.438241,4.971989e-01,0.381049,-6.235377e-01,-0.536218,0.613994,0.210785,-0.490445,0.763829,-0.248653,-0.489070,0.971569,-0.287811,0.197745,-1.073283
10,0.484195,-0.620198,6.779986e-01,0.381049,-1.741605e+00,-0.682919,0.729340,0.500177,-1.034879,0.991706,-0.174463,-0.373220,1.756676,0.612590,-0.666965,-0.675529
11,0.828139,-0.711177,1.084798e+00,1.037160,-1.741605e+00,-0.950212,0.365702,0.419345,-1.095712,1.081977,-0.406308,0.321878,1.756676,0.831529,-0.627791,0.893925
12,1.138527,-0.919128,1.175198e+00,2.021326,-1.182571e+00,-0.859457,0.576629,1.048723,-0.664435,1.092158,1.369622,0.764213,-0.049069,1.303706,0.012284,-0.549589
13,1.142721,-1.224556,8.361982e-01,0.000000,4.965218e-15,0.099069,0.928353,1.752915,0.502730,-1.387259,2.162530,0.880063,0.186463,1.242633,0.356883,1.797259
14,1.570554,-1.179067,9.943979e-01,0.000000,4.965218e-15,-0.554867,1.305800,0.899157,-0.141092,0.415199,0.215036,0.669427,-0.520133,1.354552,-0.607994,1.013758
15,1.683803,-0.672186,1.355997e+00,0.000000,4.965218e-15,-0.856970,1.693536,-0.310437,-0.703153,0.605151,0.062018,2.754721,0.186463,-0.452535,0.260428,0.478841

In [12]:
lt.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lt_no_context.csv')

In [13]:
lv = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_tcdf.csv')

lv = lv.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

lv

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-0.311469,1.886074,0.000000,6.307332e-02,-0.346022,-1.163484,-1.696134,-2.990032,-0.664315,1.063631,2.114226,0.405029,-0.434806,0.764929,-0.316476,-1.826107
1,-0.477382,1.968550,0.000000,1.429662e+00,-1.826470,-0.773394,-1.650978,-1.720628,1.298510,-0.120289,0.167927,-0.591965,1.884161,-0.210786,1.030312,-1.596740
2,-1.491290,0.758897,-1.364859,6.780382e-01,0.109501,1.723685,-0.612848,0.378443,0.245060,-1.836414,-1.685323,-1.749191,2.130860,-1.812127,1.789611,-0.398368
3,-1.583463,0.154070,-1.941705,4.047205e-01,-0.346022,2.078427,-1.521039,0.361383,-0.487596,-1.982739,-0.677279,-2.123064,-0.582826,1.824192,0.611677,-0.190980
4,-1.294653,0.667257,-1.412929,-1.440174e+00,-0.402962,1.425753,-0.806143,-0.384314,-0.052322,-0.354567,0.757244,-0.805607,-1.520280,0.434026,0.578072,0.065282
5,-0.772337,0.667257,-0.980295,-7.568799e-01,-0.061320,1.108884,-0.292147,-0.275662,-1.237061,0.655067,0.086508,-0.057861,-1.421601,0.179592,1.055192,1.023192
6,-0.563410,0.117414,-0.595731,6.307332e-02,-0.972365,0.437273,0.013809,-0.084895,-0.963173,0.747137,-0.146118,-0.200289,-1.322921,-0.324551,1.780611,0.637859
7,-0.354484,-0.982270,-0.331343,-2.102444e-01,-0.459902,-0.023513,0.380587,0.218462,-0.769502,0.529499,-0.122855,0.405029,-0.434806,-0.710705,-0.807777,1.081626
8,-0.022659,-0.835646,0.125327,-7.358554e-02,0.792784,-0.436326,0.129233,0.537105,-0.562743,0.392406,-0.262431,0.226994,0.206610,-0.370876,-0.079706,0.584138
9,0.235426,-1.394652,0.245503,-1.918480e+00,0.166441,-0.316396,0.037078,0.856875,-0.780709,0.949222,-0.979693,0.066763,-0.138768,-0.646798,-0.949254,-1.506556
10,0.567251,-0.835646,0.630067,-1.235186e+00,-0.972365,-0.354268,0.467904,0.677823,-0.599424,1.026673,0.109770,0.333815,0.009251,-0.560730,-1.038612,-1.333800
11,0.972814,-1.229699,1.158842,8.146971e-01,1.874650,-0.957708,0.700827,0.666569,-0.725640,0.788481,-0.948676,0.440636,0.601328,1.658979,-1.117413,0.353832
12,1.089567,-1.000599,1.279019,2.181286e+00,2.444053,-0.929935,0.910481,0.718120,0.464694,0.748141,-0.153872,0.636474,0.403969,1.294382,-1.187418,1.295682
13,0.849916,-0.331624,1.182878,6.068873e-15,0.000000,-0.619378,1.187638,1.026336,1.474798,-0.393089,-0.370989,0.422832,-0.237447,-0.566290,-0.928696,0.649462
14,1.495130,0.364843,0.798314,6.068873e-15,0.000000,-0.630740,1.183030,0.167005,2.261080,-1.469281,2.331344,0.120173,0.650668,0.486434,-0.654648,0.546313
15,1.661043,0.025774,1.206913,6.068873e-15,0.000000,-0.568881,1.568700,-0.152590,1.098343,-0.743876,-0.219783,2.470231,0.206610,-1.439671,0.234525,0.615164

In [14]:
lv.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/lv_no_context.csv')

In [15]:
column_index = lv.columns.get_loc('PAM')
print(column_index)

14

In [16]:
9,1,0
3,3,1
15,3,2
15,4,0
15,5,2
3,5,3
3,7,3
4,7,3
1,9,1
15,10,2
1,10,0
12,14,1
8,15,0
4,15,0
3,15,2

(3, 15, 2)

In [17]:
ee = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_tcdf.csv')

ee = ee.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

ee

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-0.226219,2.236931,0.000000,1.171421,-2.386756,-1.200121,-1.900719,-2.702926,-2.846186,2.110672,1.094372,-0.637588,-0.375920,0.799491,0.140299,-1.632853
1,-0.612028,1.701951,0.000000,1.456580,-1.607407,-0.879507,-1.596798,-1.425630,-0.443603,-0.822032,0.048857,-0.444829,-0.323160,0.238278,1.066748,-1.438183
2,-1.718691,-0.445502,-1.433676,0.860338,-0.828058,1.675435,-0.833725,0.892821,1.541880,-0.942914,0.318480,-0.415174,-0.217638,-0.624770,1.816731,0.345246
3,-1.546092,0.119617,-2.182804,0.030784,0.270115,2.594084,-0.549072,1.273566,0.621839,-0.022831,1.049758,-0.548622,-2.275308,0.629773,2.231582,0.607980
4,-1.013066,1.114227,-1.304516,-0.383993,0.128415,0.841507,-0.378208,1.109656,-0.577567,0.618564,-0.595134,-0.637588,-1.378375,0.661289,1.090742,-0.815741
5,-0.723710,0.571712,-0.762044,-0.202528,-0.828058,0.587342,-0.365302,0.023895,-0.833924,0.251857,-0.034551,-0.711726,-1.378375,0.413184,-1.079369,1.277491
6,-0.561264,0.609387,-0.503724,-1.032082,-0.898908,0.228520,-0.407109,0.198137,-0.478916,0.475846,-0.690181,-0.637588,-0.798007,1.050011,-0.818123,1.375962
7,-0.282060,0.179896,-0.271236,-1.965329,-0.225834,-0.389450,-0.266419,0.438381,-0.441191,0.872031,-0.247922,-0.430001,0.890338,0.861722,0.192162,-0.111659
8,-0.119614,-0.566061,0.167908,-2.094947,0.270115,-0.495768,0.252900,0.526286,0.301419,0.389182,-2.121702,-0.029655,0.784816,0.358168,-0.556877,-1.471272
9,0.113903,-0.483177,0.245404,-0.098834,0.872339,-0.530653,0.297434,0.433666,0.404754,0.218928,-0.794926,-0.177932,0.837577,0.243214,-0.609126,-1.035978
10,0.586011,-0.520852,0.813708,1.456580,0.872339,-0.854589,0.353055,0.634443,-0.028371,0.191677,-0.300295,0.252070,0.468252,0.607580,-0.191132,-0.583050
11,0.890597,-0.437967,0.942868,0.160402,0.872339,-0.871201,0.431580,0.200536,-0.134549,-0.107757,-0.734794,0.489312,0.943099,1.053239,-0.870372,0.167408
12,1.190107,-1.176390,1.149524,0.160402,0.872339,-0.947617,0.751497,0.558808,0.167591,0.432313,0.368913,0.311380,0.837577,-1.143743,-0.516806,1.215738
13,0.890597,-1.583276,0.787876,0.160402,0.872339,0.182006,0.449576,-0.688167,1.518591,-2.703952,0.803412,-0.029655,0.309969,-2.018328,-1.035369,0.621781
14,1.631757,-0.920203,0.839540,0.160402,0.872339,-0.117012,1.771593,-0.745360,0.862385,-0.892182,2.413389,0.044483,0.257209,-1.810134,-0.827944,0.815959
15,1.499770,-0.400293,1.511172,0.160402,0.872339,0.177023,1.989718,-0.728111,0.365850,-0.069401,-0.577676,3.603115,1.417945,-1.318973,-0.033146,0.661171

In [18]:
ee.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/ee_no_context.csv')

In [19]:
fi = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_tcdf.csv')

fi = fi.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

fi

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,1.306549,2.664653,0.000000,9.115436e-01,-0.056822,-1.124200,-1.547298,2.490889,-2.621820,2.383347,1.261917,0.813699,0.593829,1.978941,1.487967,-1.847070
1,1.410832,2.147701,0.000000,2.319472e+00,0.642522,-1.164161,-1.260630,1.839915,-1.889754,2.095611,0.842162,1.183563,1.289043,1.079015,1.428247,-1.628000
2,-1.436903,0.310171,-0.676659,1.146198e+00,0.817358,1.073692,-1.265566,0.968952,0.406666,-0.462857,-1.579680,1.035617,1.520781,0.754155,1.412352,0.241985
3,-0.610659,0.559248,-1.043026,-9.656947e-01,0.712456,1.033731,-1.052747,0.596874,0.054918,-0.665388,0.396468,0.813699,0.709698,1.651348,1.003112,-0.266153
4,-0.009025,0.018798,-0.624320,-8.483673e-01,0.607555,0.429866,-0.983264,-0.588206,-0.205513,0.082906,-1.273118,1.109590,1.404912,0.817482,0.551730,1.000117
5,-0.650768,-0.770729,-0.467306,-3.790577e-01,1.516702,-0.040794,-0.662423,-1.018597,0.505018,-0.162063,-0.306268,1.035617,0.825567,0.182258,0.759396,0.701394
6,-1.099988,-0.798926,-0.728997,-1.444030e-01,1.551669,0.381023,-0.205272,-0.700649,0.926552,-0.448807,-1.190582,0.887672,-0.796600,0.256104,0.209945,2.228601
7,-1.380750,-0.911715,-0.886011,-7.310399e-01,0.747424,0.660755,0.174991,-0.717758,0.922581,-0.624880,0.754910,0.369863,0.362091,-0.164669,-0.688570,0.603807
8,-1.340641,-0.798926,-1.095364,-2.138969e+00,0.432719,1.482190,0.288330,-0.376997,0.822942,-0.443092,1.019025,-0.369863,-0.101385,-0.538875,-1.350436,-1.050946
9,-0.634724,-0.714334,-0.781335,-3.790577e-01,0.152981,0.487588,0.233844,-0.739728,0.222855,-0.239271,-0.242597,-0.295891,-1.028338,-0.266569,-1.514837,-0.957358
10,0.327891,-0.249077,-0.362629,7.942162e-01,-0.896034,0.478708,0.597210,0.060650,-0.620948,0.100827,0.811506,-1.109590,-1.144207,-0.554345,-0.893036,0.506659
11,0.672828,-0.418261,0.736474,-3.790577e-01,-1.245706,-0.888870,0.659480,-0.623556,-0.523663,0.274618,-1.664575,-1.775344,-0.564862,-0.423990,-0.919877,0.173690
12,1.081939,-0.399463,1.207518,7.942162e-01,-1.245706,-0.813387,0.967411,0.214518,-0.281952,0.403141,0.679448,-1.479453,-1.028338,-0.759943,-1.240641,-0.180925
13,0.199542,-0.361866,0.841150,-1.042077e-14,-1.245706,0.989329,1.182318,-0.022048,0.729109,-1.912119,-0.980705,-1.331508,-0.333123,-1.242642,0.043039,-0.347795
14,1.001721,-0.361866,1.521547,-1.042077e-14,-1.245706,-0.844468,0.969689,-0.126871,1.073026,-0.646631,1.129859,-0.517809,-1.955290,-1.266289,-0.120984,0.715704
15,1.162157,0.084592,2.358959,-1.042077e-14,-1.245706,-2.141002,1.903925,-1.257387,0.479984,0.264656,0.342230,-0.369863,0.246222,-1.501981,-0.167406,0.106290

In [20]:
fi.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/fi_no_context.csv')

In [21]:
se = pd.read_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_tcdf.csv')

se = se.drop(['Unnamed: 0', 'ROL', 'GE', 'COC', 'RQ', 'SSB', 'PT'], axis=1)

se

,GDPC,VABI,EMP,QOA,QOR,YUA,REST,EBSG,GGFC,LBGD,FDI,PC,ARP,CO2C,PAM,EUPC
0,-0.563194,2.195768,-0.285704,7.891449e-01,1.012586,-0.981353,-1.430332,1.748612,-2.414350,1.916503,1.713050,-0.600088,-3.220095,1.767182,1.884165,-1.541527
1,-0.939493,1.316450,-0.049259,7.345763e-01,0.882975,-0.594512,-1.319301,1.191543,-1.514218,1.141556,1.320760,-0.427089,-1.212763,1.528212,1.892966,-1.353679
2,-2.048321,-0.523043,-1.704371,8.437134e-01,1.271808,1.364121,-0.825868,0.979037,0.577035,-0.594053,-0.394438,0.048656,-0.610563,0.719419,0.633434,0.183675
3,-1.039840,1.023344,-1.862001,1.716810e+00,1.401419,1.258249,-0.973007,0.735928,-0.889429,-0.348832,-0.947081,-0.427089,-0.342919,1.570078,0.604885,0.095005
4,-0.523056,0.891952,-0.837408,1.989653e+00,1.077391,0.451992,-0.729154,0.551917,-1.037429,-0.180811,-0.634967,-0.816335,0.058547,0.838590,-0.065834,1.720107
5,-0.773922,0.265311,-0.758593,4.617337e-01,0.558947,0.789968,-0.447442,0.495941,0.183323,-0.790137,-0.760958,-0.556838,-0.075275,0.372357,0.794102,-0.675591
6,-0.713714,-0.876791,-0.522148,-8.479110e-01,0.170114,0.753320,-0.328140,0.057093,0.866133,-1.089983,-0.912720,0.135155,0.460014,0.051732,0.872591,0.894986
7,-0.432744,-1.250754,-0.364519,-1.175322e+00,0.040503,0.468280,-0.169389,-0.546164,0.799677,-0.931249,-1.284967,0.697399,0.192369,-0.192021,-0.294786,1.918047
8,0.304802,-0.573578,0.029556,-1.557302e+00,-0.866773,-0.533432,0.000656,-0.410013,0.205352,0.056800,-0.425936,0.697399,0.660747,-0.238790,-0.190670,-1.060560
9,0.520547,-0.897005,0.581260,-1.011617e+00,-1.255606,-1.127945,0.060625,-0.984594,1.053659,0.842505,-0.122412,2.384132,0.593836,-0.374250,-0.285581,-1.355994
10,0.625911,-0.694863,1.054149,-4.659313e-01,0.040503,-1.543289,0.186767,-1.548633,0.778665,0.898704,0.312830,1.475891,0.326191,-0.553088,-0.493223,-0.295661
11,0.766396,-0.664542,1.527038,-4.659313e-01,0.688558,-1.738745,0.270438,-1.724439,0.768194,0.775304,-1.021531,0.783898,0.727658,-0.931930,-1.024339,0.702842
12,1.122625,-0.563471,1.290593,-1.011617e+00,-1.255606,-0.643376,0.567738,0.163519,0.117182,0.773928,-0.131002,0.221654,1.196035,-1.007699,-1.184273,-0.081197
13,0.500478,-1.048612,0.108370,-4.846659e-15,-1.255606,0.908057,1.257940,0.349735,1.196725,-2.154106,-0.010738,-1.724576,0.526925,-1.246951,-1.332004,0.219916
14,1.574184,0.214776,0.266000,-4.846659e-15,-1.255606,1.193097,1.640184,0.457823,-0.012566,-0.619626,1.621420,-0.859585,0.259280,-0.946329,-1.346396,0.148523
15,1.619340,1.185058,1.527038,-4.846659e-15,-1.255606,-0.024432,2.238285,-1.517303,-0.677953,0.303496,1.678689,-1.032583,0.460014,-1.356513,-0.465036,0.481109

In [22]:
se.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/y/se_no_context.csv')