In [1]:
import pandas as pd
import numpy as np

In [2]:
sw = pd.read_csv("/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden.csv")

In [3]:
sw = sw.drop(["Unnamed: 0"], axis=1)

In [4]:
sw_2007_2015 = sw.loc[7:15]

In [5]:
sw_2007_2015

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
7,2007,1.89,2.02,2.23,1.57,1.51,93.0,0.979,0.973,82.0,...,6.34,NaN,3.0,16.0,90.973078,79.601798,56.666667,80.863303,66.054195,NaN
8,2008,1.92,1.95,2.21,1.64,1.52,93.0,0.979,0.973,90.0,...,6.23,NaN,3.0,16.0,91.142842,79.794474,56.666667,81.042448,66.054195,NaN
9,2009,1.96,2.04,2.24,1.65,1.55,92.0,0.979,0.973,91.0,...,6.23,NaN,3.0,16.0,91.197065,79.917379,56.666667,81.042448,66.054195,NaN
10,2010,1.93,1.96,2.22,1.66,1.54,92.0,0.979,0.973,90.0,...,6.47,81.241760,3.0,16.0,91.309258,79.981417,56.666667,80.982778,68.195515,NaN
11,2011,1.92,1.93,2.17,1.89,1.61,93.0,0.977,0.973,92.8,...,6.31,82.606503,3.0,16.0,92.163977,79.845455,63.333333,81.946012,68.195515,NaN
12,2012,1.93,1.91,2.28,1.90,1.69,88.0,0.977,0.978,93.2,...,5.98,82.272774,3.0,16.0,92.214270,80.073254,63.333333,81.946012,68.195515,NaN
13,2013,1.95,1.79,2.24,1.90,1.66,89.0,0.976,0.978,94.8,...,5.94,82.167304,3.0,16.0,92.263776,83.179328,63.333333,81.946012,68.195515,NaN
14,2014,1.98,1.68,2.11,1.81,1.61,87.0,0.976,0.978,92.5,...,5.63,80.978516,3.0,16.0,92.275829,83.233922,72.000000,81.952862,68.004258,NaN
15,2015,1.99,1.68,2.15,1.80,1.57,89.0,0.974,0.974,90.6,...,5.63,81.394674,3.0,16.0,92.291100,77.477318,72.000000,83.459378,67.309814,7.0

In [6]:
def missing_values(df):
    for feature in df.columns:
        missing_values = df[feature].isna().sum()
        percentage = missing_values/len(df) * 100
        print(f'{feature} - {missing_values} - {round(percentage, 1)} %')

In [7]:
missing_values(sw_2007_2015)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 4 - 44.4 %
PR - 0 - 0.0 %
DI - 2 - 22.2 %
SOARS - 0 - 0.0 %
TOGP - 0 - 0.0 %
IPAB - 3 - 33.3 %
PTIP - 0 - 0.0 %
QOES - 0 - 0.0 %
AOLT - 0 - 0.0 %
FLTA - 0 - 0.0 %
EBOF - 0 - 0.0 %
FOWD - 0 - 0.0 %
QOMS - 0 - 0.0 %
CLER - 0 - 0.0 %
WTDA - 0 - 0.0 %
EDBS - 3 - 33.3 %
DBP - 0 - 0.0 %
DBD - 0 - 0.0 %
SSB - 0 - 0.0 %
DWCP - 0 - 0.0 %
PMSI - 0 - 0.0 %
PT - 0 - 0.0 %
EC - 0 - 0.0 %
ELFE - 8 - 88.9 %

In [8]:
mode = sw_2007_2015['DI'].mode()[0]
sw_2007_2015['DI'].fillna(value=mode, inplace=True)

/var/folders/41/w_0mz3gn2vn0w0dz8wywr8_r0000gn/T/ipykernel_74564/3850783321.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sw_2007_2015['DI'].fillna(value=mode, inplace=True)

In [9]:
sw_2007_2015 = sw_2007_2015.drop(["ELFE", "CFI", "IPAB", "EDBS"], axis=1)

In [10]:
def fill_with_mean(df):
    for feature in df.columns:
        mean = df[feature].mean()
        df[feature].fillna(value=mean, inplace=True)

In [11]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [12]:
def handle_outliers(df, continuous_features):

    print("Original Shape:", df.shape)
    
    outlier_summary = {}
    
    for feature in continuous_features:
        if feature in df.columns:
            Q1 = df[feature].quantile(0.25)
            Q3 = df[feature].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            
            outlier_mask = (df[feature] < lower_bound) | (df[feature] > upper_bound)
            num_outliers = outlier_mask.sum()
            
            if num_outliers > 0:
                non_outlier_mean = df.loc[~outlier_mask, feature].mean()
                
                df.loc[outlier_mask, feature] = non_outlier_mean
                
                print(f"{feature}: Found {num_outliers} outliers, replaced with mean = {non_outlier_mean:.2f}")
            else:
                print(f"{feature}: No outliers found")
    
    print("\nFinal Shape:", df.shape)
    print(f"Total features processed: {len(continuous_features)}")
    
    return df

In [13]:
sw_2007_2015_no_o = handle_outliers(sw_2007_2015, continuous_data)

Original Shape: (9, 30)
DBP: No outliers found
DBD: No outliers found
SSB: No outliers found
DWCP: Found 3 outliers, replaced with mean = 79.87
PT: Found 1 outliers, replaced with mean = 81.47
EC: No outliers found
IUI: Found 1 outliers, replaced with mean = 91.86
PMSI: No outliers found

Final Shape: (9, 30)
Total features processed: 9

In [14]:
sw_2007_2015_no_o

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,QOMS,CLER,WTDA,DBP,DBD,SSB,DWCP,PMSI,PT,EC
7,2007,1.89,2.02,2.23,1.57,1.51,93.0,0.979,0.973,91.8625,...,5.47,5.56,6.34,3.0,16.0,90.973078,79.601798,56.666667,80.863303,66.054195
8,2008,1.92,1.95,2.21,1.64,1.52,93.0,0.979,0.973,90.0000,...,5.40,5.72,6.23,3.0,16.0,91.142842,79.794474,56.666667,81.042448,66.054195
9,2009,1.96,2.04,2.24,1.65,1.55,92.0,0.979,0.973,91.0000,...,5.40,5.86,6.23,3.0,16.0,91.197065,79.917379,56.666667,81.042448,66.054195
10,2010,1.93,1.96,2.22,1.66,1.54,92.0,0.979,0.973,90.0000,...,5.63,5.86,6.47,3.0,16.0,91.309258,79.981417,56.666667,80.982778,68.195515
11,2011,1.92,1.93,2.17,1.89,1.61,93.0,0.977,0.973,92.8000,...,5.54,5.66,6.31,3.0,16.0,92.163977,79.845455,63.333333,81.946012,68.195515
12,2012,1.93,1.91,2.28,1.90,1.69,88.0,0.977,0.978,93.2000,...,5.42,5.57,5.98,3.0,16.0,92.214270,80.073254,63.333333,81.946012,68.195515
13,2013,1.95,1.79,2.24,1.90,1.66,89.0,0.976,0.978,94.8000,...,5.38,5.65,5.94,3.0,16.0,92.263776,79.868963,63.333333,81.946012,68.195515
14,2014,1.98,1.68,2.11,1.81,1.61,87.0,0.976,0.978,92.5000,...,5.16,5.37,5.63,3.0,16.0,92.275829,79.868963,72.000000,81.952862,68.004258
15,2015,1.99,1.68,2.15,1.80,1.57,89.0,0.974,0.974,90.6000,...,5.36,5.65,5.63,3.0,16.0,92.291100,79.868963,72.000000,81.465234,67.309814

In [15]:
sw_2007_2015_no_o.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2007_2015.csv')

In [16]:
sw_2007_2015_no_o = sw_2007_2015_no_o.drop(["TIME_PERIOD"], axis=1)

In [17]:
sw_2007_2015_l = sw_2007_2015_no_o.loc[13]

In [18]:
sw_2007_2015_l.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2007_2013_last.csv')

In [19]:
sw_2016_2022 = sw.loc[16:22]

In [20]:
sw_2016_2022

,TIME_PERIOD,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,...,WTDA,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
16,2016,1.95,1.66,2.11,1.84,1.57,88.0,0.973,0.974,89.7,...,5.63,81.632083,3.0,7.0,94.612286,77.680732,72.0,85.281398,67.609776,7.4
17,2017,1.82,1.68,2.10,1.79,1.57,84.0,0.973,0.974,93.0,...,NaN,82.150712,3.0,7.0,94.640268,77.775788,72.0,85.279351,67.609776,7.7
18,2018,1.78,1.67,2.11,1.83,1.58,85.0,0.964,0.974,89.2,...,NaN,82.174910,3.0,7.0,94.668857,77.891382,72.0,85.279351,67.609776,7.5
19,2019,1.79,1.67,2.09,1.79,1.56,85.0,0.964,0.974,94.5,...,NaN,82.018479,4.0,7.5,93.089838,77.972100,72.0,85.279351,67.609776,6.5
20,2020,1.77,1.67,2.09,1.68,1.50,85.0,0.962,0.974,94.5,...,NaN,81.558564,4.0,7.5,93.111728,78.045257,72.0,85.283436,67.609776,7.7
21,2021,1.70,1.61,2.10,1.75,1.49,85.0,0.965,0.966,94.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.4
22,2022,1.69,1.57,2.06,1.68,1.53,83.0,0.959,0.977,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.8

In [21]:

missing_values(sw_2016_2022)

TIME_PERIOD - 0 - 0.0 %
ROL - 0 - 0.0 %
GE - 0 - 0.0 %
COC - 0 - 0.0 %
RQ - 0 - 0.0 %
VAA - 0 - 0.0 %
CPI - 0 - 0.0 %
FOP - 0 - 0.0 %
JI - 0 - 0.0 %
IUI - 0 - 0.0 %
CFI - 0 - 0.0 %
PR - 0 - 0.0 %
DI - 0 - 0.0 %
SOARS - 5 - 71.4 %
TOGP - 5 - 71.4 %
IPAB - 5 - 71.4 %
PTIP - 5 - 71.4 %
QOES - 5 - 71.4 %
AOLT - 5 - 71.4 %
FLTA - 5 - 71.4 %
EBOF - 5 - 71.4 %
FOWD - 5 - 71.4 %
QOMS - 5 - 71.4 %
CLER - 5 - 71.4 %
WTDA - 6 - 85.7 %
EDBS - 2 - 28.6 %
DBP - 2 - 28.6 %
DBD - 2 - 28.6 %
SSB - 2 - 28.6 %
DWCP - 2 - 28.6 %
PMSI - 2 - 28.6 %
PT - 2 - 28.6 %
EC - 2 - 28.6 %
ELFE - 0 - 0.0 %

In [22]:
sw_2016_2022 = sw_2016_2022.drop(["SOARS", "TOGP", "IPAB", "PTIP", "QOES", "AOLT", "FLTA", "EBOF",
                                 "FOWD", "QOMS", "CLER", "WTDA"], axis=1)

In [23]:
sw_2016_2022["EC"]

16    67.609776
17    67.609776
18    67.609776
19    67.609776
20    67.609776
21          NaN
22          NaN
Name: EC, dtype: float64

In [24]:
mode = sw_2007_2015['PMSI'].mode()[0]
sw_2007_2015['PMSI'].fillna(value=mode, inplace=True)
mode = sw_2007_2015['EC'].mode()[0]
sw_2007_2015['EC'].fillna(value=mode, inplace=True)

In [25]:
fill_with_mean(sw_2016_2022)

In [26]:
continuous_data = ['DBP', "DBD", "EDBS", "SSB", "DWCP", "PT", "EC", "IUI", "PMSI"]

In [27]:
sw_2016_2022_no_o = handle_outliers(sw_2016_2022, continuous_data)

Original Shape: (7, 22)
DBP: No outliers found
DBD: No outliers found
EDBS: No outliers found
SSB: No outliers found
DWCP: No outliers found
PT: No outliers found
EC: No outliers found
IUI: No outliers found
PMSI: No outliers found

Final Shape: (7, 22)
Total features processed: 9

In [28]:
sw_2016_2022_no_o.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2016_2022.csv')

In [29]:
sw_2016_2022_no_o = sw_2016_2022_no_o.drop(["TIME_PERIOD"], axis=1)

In [30]:
sw_2016_2022_no_o

,ROL,GE,COC,RQ,VAA,CPI,FOP,JI,IUI,CFI,...,DI,EDBS,DBP,DBD,SSB,DWCP,PMSI,PT,EC,ELFE
16,1.95,1.66,2.11,1.84,1.57,88.0,0.973,0.974,89.7,63.6,...,9.39,81.632083,3.0,7.0,94.612286,77.680732,72.0,85.281398,67.609776,7.4
17,1.82,1.68,2.10,1.79,1.57,84.0,0.973,0.974,93.0,63.8,...,9.39,82.150712,3.0,7.0,94.640268,77.775788,72.0,85.279351,67.609776,7.7
18,1.78,1.67,2.11,1.83,1.58,85.0,0.964,0.974,89.2,63.1,...,9.39,82.174910,3.0,7.0,94.668857,77.891382,72.0,85.279351,67.609776,7.5
19,1.79,1.67,2.09,1.79,1.56,85.0,0.964,0.974,94.5,63.7,...,9.39,82.018479,4.0,7.5,93.089838,77.972100,72.0,85.279351,67.609776,6.5
20,1.77,1.67,2.09,1.68,1.50,85.0,0.962,0.974,94.5,62.5,...,9.26,81.558564,4.0,7.5,93.111728,78.045257,72.0,85.283436,67.609776,7.7
21,1.70,1.61,2.10,1.75,1.49,85.0,0.965,0.966,94.7,63.1,...,9.26,81.906949,3.4,7.2,94.024595,77.873052,72.0,85.280577,67.609776,8.4
22,1.69,1.57,2.06,1.68,1.53,83.0,0.959,0.977,95.0,61.6,...,9.39,81.906949,3.4,7.2,94.024595,77.873052,72.0,85.280577,67.609776,8.8

In [31]:
sw_2016_2022_l = sw_2016_2022_no_o.loc[20]

In [32]:
sw_2016_2022_l

ROL      1.770000
GE       1.670000
COC      2.090000
RQ       1.680000
VAA      1.500000
CPI     85.000000
FOP      0.962000
JI       0.974000
IUI     94.500000
CFI     62.500000
PR      89.000000
DI       9.260000
EDBS    81.558564
DBP      4.000000
DBD      7.500000
SSB     93.111728
DWCP    78.045257
PMSI    72.000000
PT      85.283436
EC      67.609776
ELFE     7.700000
Name: 20, dtype: float64

In [33]:
sw_2016_2022_l.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2014_2020_last.csv')

In [35]:
se_2022 = sw_2016_2022_no_o.loc[22]

In [36]:
se_2022.to_csv('/Users/vladasverkelis/Documents/Doktorantūra/Straipsnis_1/Context_influance_to_EU_structural_funds/Data/Context/Sweden_2022.csv')